"""start

Revision ID: eba9660dbaac
Revises: 
Create Date: 2025-03-12 07:24:47.093169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba9660dbaac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.Text(), nullable=False),
    sa.Column('oop', sa.Float(), nullable=False),
    sa.Column('ro', sa.Float(), nullable=False),
    sa.Column('net', sa.Float(), nullable=False),
    sa.Column('comp', sa.Float(), nullable=False),
    sa.Column('database', sa.Float(), nullable=False),
    sa.Column('si', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    # ### end Alembic commands ###
